### ISSUE TITLE
Jack-o'-lantern (pumpkin lantern) making workshop

### ISSUE THREAD

**Issue by BillShiyaoZhang** [BillShiyaoZhang/DI-2019#1]
Anyone who wants to make Jack-o'-lantern (pumpkin lantern) tomorrow (Wednesday) comments below 😄 
Come with your materials, or we could buy them together after your CSDI I 😄

**Comment by c-chen-ed5557** [comment]
Such a quiet place.
(I'm in.)

**Comment by DiwenYudd** [comment]
I am in!  
I wanna make another one（as an experienced pumpkin carver）

**Comment by shixuanwang** [comment]
I'm in !
Though I'm not a big fan of eating Pumpkin, good for just play with!

**Comment by shixuanwang** [comment]
I'm in!
Though I'm not a big fan of eating pumpkin, good for just playing with!

**Comment by Dandi-H** [comment]
Awwww count me in!

**Comment by tbb9613** [comment]
I'm in :)

**Comment by dododepp** [comment]
I’m in🙋

**Comment by 971105-vicky** [comment]
🙋🏻‍♀️🙋🏻‍♀️🙋🏻‍♀️I'm in

**Comment by 1kellylucia** [comment]
I'm in .

**Comment by yvetteyy** [comment]
I'm in
